# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Html2markdown < Formula
  desc ""
  homepage ""
  version "2.0.2-alpha"

  on_macos do
    on_intel do
      url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.2-alpha/html-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "78854ec9949b2e90824933336b89299de489cb44f0b51c50772ec3977269f93e"

      def install
        bin.install "html2markdown"
      end
    end
    on_arm do
      url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.2-alpha/html-to-markdown_Darwin_arm64.tar.gz"
      sha256 "06da141891661a801a24200c116c1ea84bd9c8e2d41007e7b0d3a55cff7b83d9"

      def install
        bin.install "html2markdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.2-alpha/html-to-markdown_Linux_x86_64.tar.gz"
        sha256 "0a1b4b0b911bf94fbe87181866ab19dc46afe293a270a4de5d0c8f3f571b99f4"

        def install
          bin.install "html2markdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.2-alpha/html-to-markdown_Linux_arm64.tar.gz"
        sha256 "e72153bd57dc4b5bb0133d7ff52a3a899ad2a256662830c780fd41a0ff89e391"

        def install
          bin.install "html2markdown"
        end
      end
    end
  end
end
