# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Html2markdown < Formula
  desc ""
  homepage ""
  version "2.0.3-alpha"

  on_macos do
    on_intel do
      url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.3-alpha/html-to-markdown_Darwin_x86_64.tar.gz"
      sha256 "0ef0c6a84f2aa8c1d74ca5241e1e7d4f086c361c3ad81b667a05d456e235b04d"

      def install
        bin.install "html2markdown"
      end
    end
    on_arm do
      url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.3-alpha/html-to-markdown_Darwin_arm64.tar.gz"
      sha256 "1ec2856c45eb4fda939673f77f1deb8b2a5aa46a7b6410e9df009e45c676747c"

      def install
        bin.install "html2markdown"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.3-alpha/html-to-markdown_Linux_x86_64.tar.gz"
        sha256 "7fa81c737fcc36c66378c4f89bc072888453a92304d8b4db2550d490742b3f61"

        def install
          bin.install "html2markdown"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/JohannesKaufmann/html-to-markdown/releases/download/v2.0.3-alpha/html-to-markdown_Linux_arm64.tar.gz"
        sha256 "a0d98f08e39257ad19387cfc7d87e2b37f81e5f2d79b27e67ec1482a3a705de2"

        def install
          bin.install "html2markdown"
        end
      end
    end
  end
end
